---
- name: Remove Chrome Remote Desktop package
  apt:
    name: chrome-remote-desktop
    state: absent
 
- name: Remove the Debian Linux Chrome Remote Desktop installation package file
  file:
    path: /tmp/chrome-remote-desktop_current_amd64.deb
    state: absent
 
- name: Uninstall Ubuntu desktop environment
  shell: DEBIAN_FRONTEND=noninteractive tasksel remove ubuntu-desktop
  become: yes
 
- name: Remove Chrome Remote Desktop session file
  file:
    path: /etc/chrome-remote-desktop-session
    state: absent
  become: yes
